#!/bin/sh
cd ~/projects/blog/

tmux start-server
tmux new-session -d -s blog -n vim  

tmux selectp -t 1
tmux send-keys "cd~/project/blog/;vim" C-m

tmux splitw -h -p 10 

tmux attach-session -t blog



